[project]
authors = ["Davoody, Amirhossein <amirhossein.davoody@intel.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "cpp_project"
platforms = ["linux-64"]
version = "0.1.0"

[system-requirements]
libc = {family = "glibc", version = "2.22"}
linux = "4.12.14"

[dependencies]
clang-format = ">=20.1.2,<21"
clang-tools = ">=20.1.2,<21"
clangxx = ">=20.1.2,<21"
cmake = ">=3.30.1,<3.31"
cmake-format = ">=0.6.13,<0.7"
compiler-rt = ">=20.1.7,<21"
cxx-compiler = ">=1.9.0,<2"
include-what-you-use = ">=0.24,<0.25"
libcxx = ">=19.1.7,<20"
llvm-tools = ">=20.1.6,<21"
ninja = ">=1.12.1,<2"
python = ">=3.13.3,<3.14"
