[workspace]
authors = ["Davoody, Amirhossein <amirhossein.davoody@intel.com>"]
channels = ["conda-forge"]
name = "parser"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
rust = ">=1.88.0,<1.89"
rust-src = ">=1.88.0,<2"
